// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "vitest";

function describe(prim0, prim1) {
  Vitest.describe(prim0, prim1);
}

function test(prim0, prim1) {
  Vitest.it(prim0, prim1);
}

function testAsync(prim0, prim1) {
  Vitest.it(prim0, prim1);
}

function expectIntEqual(actual, expected) {
  Vitest.expect(actual).toBe(expected);
}

function expectFloatEqual(actual, expected) {
  Vitest.expect(actual).toBe(expected);
}

function expectFloatGreater(actual, expected) {
  Vitest.expect(actual).toBeGreaterThan(expected);
}

function expectFloatLess(actual, expected) {
  Vitest.expect(actual).toBeLessThan(expected);
}

function expectFloatCloseTo(actual, expected) {
  Vitest.expect(actual).toBeCloseTo(expected);
}

export {
  describe ,
  test ,
  testAsync ,
  expectIntEqual ,
  expectFloatEqual ,
  expectFloatGreater ,
  expectFloatLess ,
  expectFloatCloseTo ,
}
/* vitest Not a pure module */
