// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Schema from "./Schema.bs.mjs";
import * as Database from "./Database.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";
import * as Database$1 from "firebase/database";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let dartsModeSchema = Schema.union([
  Schema.object(s => {
    s.tag("kind", "r");
    return "AroundTheClock";
  }),
  Schema.object(s => {
    s.tag("kind", "b");
    return "Bullen";
  }),
  Schema.object(s => {
    s.tag("kind", "k");
    return "Killer";
  }),
  Schema.object(s => {
    s.tag("kind", "5");
    return "M501";
  }),
  Schema.object(s => {
    s.tag("kind", "3");
    return "M301";
  })
]);

function dartsModeToString(dartsMode) {
  switch (dartsMode) {
    case "AroundTheClock" :
      return "Around the Cock";
    case "Bullen" :
      return "Bullen";
    case "Killer" :
      return "Killer";
    case "M501" :
      return "501";
    case "M301" :
      return "301";
    case "Unknown" :
      return "Unknown";
  }
}

let dartsGameSchema = Schema.object(s => ({
  winners: s.f("w", Schema.array(Schema.string)),
  losers: s.f("l", Schema.array(Schema.string)),
  date: s.f("d", Schema.transform(Schema.float, param => ({
    p: prim => new Date(prim),
    s: prim => prim.getTime()
  }))),
  mode: s.f("m", dartsModeSchema)
}));

function addDartsGame(dartsGame) {
  let dartsGamesRef = Database$1.ref(Database.database, "dartsGames");
  try {
    let data = Schema.convertToJsonOrThrow(dartsGame, dartsGameSchema);
    return Database$1.push(dartsGamesRef, data);
  } catch (exn) {
    return RescriptCore.panic("Could not create darts game");
  }
}

async function fetchAllGames() {
  let games = await Database$1.get(Database$1.query(Database$1.ref(Database.database, "dartsGames"), Database$1.orderByChild("date")));
  let orderedGames = [];
  games.forEach(snap => {
    let val = snap.val();
    if (val == null) {
      return;
    }
    try {
      let val$1 = Schema.parseOrThrow(val, dartsGameSchema);
      orderedGames.push(val$1);
      return;
    } catch (raw_e) {
      let e = Primitive_exceptions.internalToException(raw_e);
      console.log(e);
      return;
    }
  });
  return orderedGames;
}

function removeGame(gameKey) {
  return Database$1.remove(Database$1.ref(Database.database, "dartsGames/" + gameKey));
}

let empty = {};

function useLastGames() {
  let match = React.useState(() => empty);
  let setGames = match[1];
  let gamesRef = Database$1.query(Database$1.ref(Database.database, "dartsGames"), Database$1.orderByChild("date"));
  React.useEffect(() => Database$1.onValue(gamesRef, snapshot => {
    let val = snapshot.val();
    let games;
    if (val == null) {
      games = empty;
    } else {
      try {
        games = Schema.parseOrThrow(val, Schema.dict(dartsGameSchema));
      } catch (raw_e) {
        let e = Primitive_exceptions.internalToException(raw_e);
        console.log(e);
        games = empty;
      }
    }
    setGames(param => games);
  }, undefined), [setGames]);
  return match[0];
}

export {
  addDartsGame,
  dartsModeToString,
  fetchAllGames,
  removeGame,
  useLastGames,
}
/* dartsModeSchema Not a pure module */
