// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as App from "firebase/app";
import * as Auth from "firebase/auth";
import * as Database from "firebase/database";

let databaseURL = process.env.NEXT_PUBLIC_DATABASE_URL;

let config = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  databaseURL: databaseURL,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_MEASUREMENT_ID
};

let app = App.initializeApp(config);

let database = Database.getDatabase(app);

let auth = Auth.getAuth();

function useUser() {
  let match = React.useState(() => auth.currentUser);
  let setUser = match[1];
  React.useEffect(() => Auth.onAuthStateChanged(auth, user => setUser(param => user), undefined, undefined), []);
  return match[0];
}

export {
  app,
  database,
  auth,
  useUser,
  databaseURL,
}
/* databaseURL Not a pure module */
