// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as App from "firebase/app";
import * as Auth from "firebase/auth";
import * as Database from "firebase/database";

var databaseURL = process.env.NEXT_PUBLIC_DATABASE_URL;

var config = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  databaseURL: databaseURL,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_MEASUREMENT_ID
};

var isClient = (typeof window !== 'undefined');

var app = isClient ? App.initializeApp(config) : undefined;

var database = isClient ? Database.getDatabase(app) : undefined;

var auth = isClient ? Auth.getAuth() : undefined;

function useUser() {
  var initialUser = isClient ? auth.currentUser : null;
  var match = React.useState(function () {
        return initialUser;
      });
  var setUser = match[1];
  React.useEffect((function () {
          if (isClient) {
            return Auth.onAuthStateChanged(auth, (function (user) {
                          setUser(function (param) {
                                return user;
                              });
                        }), undefined, undefined);
          }
          
        }), []);
  return match[0];
}

export {
  app ,
  database ,
  auth ,
  useUser ,
  databaseURL ,
}
/* databaseURL Not a pure module */
