// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as App from "firebase/app";
import * as Auth from "firebase/auth";
import * as Database from "firebase/database";

var config = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  databaseURL: process.env.NEXT_PUBLIC_DATABASE_URL,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_MEASUREMENT_ID
};

var app = App.initializeApp(config);

var database = Database.getDatabase(app);

var auth = Auth.getAuth();

function useUser() {
  var match = React.useState(function () {
        return auth.currentUser;
      });
  var setUser = match[1];
  React.useEffect((function () {
          return Auth.onAuthStateChanged(auth, (function (user) {
                        setUser(function (param) {
                              return user;
                            });
                      }), undefined, undefined);
        }), []);
  return match[0];
}

export {
  app ,
  database ,
  auth ,
  useUser ,
}
/* config Not a pure module */
