// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Schema from "./Schema.bs.mjs";
import * as Database from "./Database.bs.mjs";
import * as Mattermost from "./Mattermost.bs.mjs";
import * as Database$1 from "firebase/database";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let daysWithoutSchema = Schema.object(s => ({
  name: s.fieldOr("name", Schema.string, "Days without an accident"),
  date: s.f("date", Schema.transform(Schema.float, param => ({
    p: prim => new Date(prim),
    s: prim => prim.getTime()
  })))
}));

function useDaysWithout() {
  let match = React.useState(() => "");
  let setName = match[1];
  let match$1 = React.useState(() => new Date());
  let setDate = match$1[1];
  React.useEffect(() => {
    let daysWithoutRef = Database$1.ref(Database.database, "daysWithout");
    return Database$1.onValue(daysWithoutRef, snapshot => {
      let data = snapshot.val();
      if (data == null) {
        console.log("No data");
        return;
      }
      try {
        let daysWithout = Schema.parseOrThrow(data, daysWithoutSchema);
        setName(param => daysWithout.name);
        return setDate(param => daysWithout.date);
      } catch (raw_error) {
        let error = Primitive_exceptions.internalToException(raw_error);
        console.log(error);
        return;
      }
    }, undefined);
  }, []);
  return [
    match[0],
    match$1[0]
  ];
}

async function reset() {
  let daysWithoutRef = Database$1.ref(Database.database, "daysWithout/date");
  await Database$1.set(daysWithoutRef, Date.now());
  let daysWithoutRef$1 = Database$1.ref(Database.database, "daysWithout");
  let daysWithoutVal = await Database$1.get(daysWithoutRef$1);
  let name;
  try {
    let val = daysWithoutVal.val();
    name = (val == null) ? "Days without an accident" : Schema.parseOrThrow(val, daysWithoutSchema).name;
  } catch (exn) {
    name = "Days without an accident";
  }
  Mattermost.sendDaysWithoutReset(name);
}

export {
  reset,
  useDaysWithout,
}
/* daysWithoutSchema Not a pure module */
