// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DomUtils from "../helpers/dom-utils";

function getMultiSelectValues(prim) {
  return DomUtils.getMultiSelectValues(prim);
}

export {
  getMultiSelectValues ,
}
/* ../helpers/dom-utils Not a pure module */
