// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Schema from "./Schema.bs.mjs";
import * as Database from "./Database.bs.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";
import * as Database$1 from "firebase/database";

var fifaGameSchema = Schema.object(function (s) {
      return {
              blueScore: s.f("bs", Schema.$$int),
              redScore: s.f("rs", Schema.$$int),
              blueTeam: s.f("bt", Schema.array(Schema.string)),
              redTeam: s.f("rt", Schema.array(Schema.string)),
              date: s.f("d", Schema.transform(Schema.$$float, (function (param) {
                          return {
                                  p: (function (prim) {
                                      return new Date(prim);
                                    }),
                                  s: (function (prim) {
                                      return prim.getTime();
                                    })
                                };
                        })))
            };
    });

function addFifaGame(fifaGame) {
  var fifaGamesRef = Database$1.ref(Database.database, "fifaGames");
  var data = Schema.serializeWith(fifaGame, fifaGameSchema);
  if (data.TAG === "Ok") {
    return Database$1.push(fifaGamesRef, data._0);
  } else {
    return RescriptCore.panic("Could not create FIFA game");
  }
}

async function fetchAllGames() {
  var games = await Database$1.get(Database$1.query(Database$1.ref(Database.database, "fifaGames"), Database$1.orderByChild("date")));
  return Core__Array.filterMap(games, (function (snap) {
                var val = snap.val();
                if (val == null) {
                  return ;
                }
                var val$1 = Schema.parseWith(val, fifaGameSchema);
                if (val$1.TAG === "Ok") {
                  return val$1._0;
                }
                console.log(val$1._0);
              }));
}

function removeGame(gameKey) {
  return Database$1.remove(Database$1.ref(Database.database, "fifaGames/" + gameKey));
}

var empty = {};

function useLastGames() {
  var match = React.useState(function () {
        return empty;
      });
  var setGames = match[1];
  var gamesRef = Database$1.query(Database$1.ref(Database.database, "fifaGames"), Database$1.orderByChild("date"));
  React.useEffect((function () {
          return Database$1.onValue(gamesRef, (function (snapshot) {
                        var val = snapshot.val();
                        var games;
                        if (val == null) {
                          games = empty;
                        } else {
                          var val$1 = Schema.parseWith(val, Schema.dict(fifaGameSchema));
                          if (val$1.TAG === "Ok") {
                            games = val$1._0;
                          } else {
                            console.log(val$1._0);
                            games = {};
                          }
                        }
                        setGames(function (param) {
                              return games;
                            });
                      }), undefined);
        }), [setGames]);
  return match[0];
}

export {
  addFifaGame ,
  fetchAllGames ,
  removeGame ,
  useLastGames ,
}
/* fifaGameSchema Not a pure module */
