// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Database from "./Database.bs.mjs";
import * as Database$1 from "firebase/database";
import * as FirebaseNetworkFix from "./firebase-network-fix";

function useFirebaseStatus() {
  var match = React.useState(function () {
        return false;
      });
  var setStatus = match[1];
  FirebaseNetworkFix.useFirebaseNetworkFix();
  React.useEffect((function () {
          var ref = Database$1.ref(Database.database, ".info/connected");
          return Database$1.onValue(ref, (function (snap) {
                        var value = snap.val();
                        if (value == null) {
                          return setStatus(function (param) {
                                      return false;
                                    });
                        }
                        var match = Js_json.decodeBoolean(value);
                        if (match !== undefined && match) {
                          return setStatus(function (param) {
                                      return true;
                                    });
                        }
                        setStatus(function (param) {
                              return false;
                            });
                      }), undefined);
        }), []);
  return match[0];
}

export {
  useFirebaseStatus ,
}
/* react Not a pure module */
