// Generated by ReScript, PLEASE EDIT WITH CARE


var Auth = {};

var Snapshot = {};

var Database = {
  Snapshot: Snapshot
};

var Firebase = {
  Auth: Auth,
  Database: Database
};

export {
  Firebase ,
}
/* No side effect */
