// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Schema from "./Schema.bs.mjs";
import * as Database from "./Database.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";
import * as FirebaseSchema from "./FirebaseSchema.bs.mjs";
import * as Database$1 from "firebase/database";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let modifierSchema = Schema.union([
  Schema.object(s => {
    s.tag("kind", "handicap");
    return {
      TAG: "Handicap",
      _0: s.f("blue", Schema.int),
      _1: s.f("red", Schema.int)
    };
  }),
  Schema.object(s => {
    s.tag("kind", "one-v-one");
    return "OneVOne";
  })
]);

let gameSchema = Schema.object(s => ({
  blueScore: s.f("blueScore", Schema.intMin(Schema.int, 0, undefined)),
  redScore: s.f("redScore", Schema.intMin(Schema.int, 0, undefined)),
  blueTeam: s.f("blueTeam", Schema.array(Schema.string)),
  redTeam: s.f("redTeam", Schema.array(Schema.string)),
  date: s.f("date", Schema.transform(Schema.float, param => ({
    p: prim => new Date(prim),
    s: prim => prim.getTime()
  }))),
  modifiers: s.f("modifiers", FirebaseSchema.nullableTransform(Schema.option(Schema.array(modifierSchema))))
}));

function addGame(game) {
  let gamesRef = Database$1.ref(Database.database, "games");
  try {
    let data = Schema.convertToJsonOrThrow(game, gameSchema);
    return Database$1.push(gamesRef, data);
  } catch (exn) {
    return RescriptCore.panic("Could not create game");
  }
}

async function getTimePeriod(period) {
  let date = new Date();
  date.setHours(0, 0, 0, 0);
  switch (period) {
    case "Daily" :
      break;
    case "Weekly" :
      let x = date.getDay();
      let newDate = (date.getDate() - (
        x === 0 ? 7 : x
      ) | 0) + 1 | 0;
      date.setDate(newDate);
      break;
    case "Monthly" :
      date.setDate(0);
      break;
    case "All" :
      date.setFullYear(2000);
      break;
  }
  let games = await Database$1.get(Database$1.query(Database$1.ref(Database.database, "games"), Database$1.orderByChild("date"), Database$1.startAt(date.getTime())));
  let val = games.val();
  if (val == null) {
    return {};
  }
  try {
    return Schema.parseOrThrow(val, Schema.dict(gameSchema));
  } catch (raw_e) {
    let e = Primitive_exceptions.internalToException(raw_e);
    console.log(e);
    return {};
  }
}

let empty = {};

function useLastGames() {
  let match = React.useState(() => empty);
  let setGames = match[1];
  let gamesRef = Database$1.query(Database$1.ref(Database.database, "games"), Database$1.orderByChild("date"));
  React.useEffect(() => Database$1.onValue(gamesRef, snapshot => {
    let val = snapshot.val();
    let games;
    if (val == null) {
      games = empty;
    } else {
      try {
        games = Schema.parseOrThrow(val, Schema.dict(gameSchema));
      } catch (raw_e) {
        let e = Primitive_exceptions.internalToException(raw_e);
        console.log(e);
        games = empty;
      }
    }
    setGames(param => games);
  }, undefined), [setGames]);
  return match[0];
}

async function fetchAllGames() {
  let games = await Database$1.get(Database$1.query(Database$1.ref(Database.database, "games"), Database$1.orderByChild("date")));
  let orderedGames = [];
  games.forEach(snap => {
    let val = snap.val();
    if (val == null) {
      return;
    }
    try {
      let val$1 = Schema.parseOrThrow(val, gameSchema);
      orderedGames.push(val$1);
      return;
    } catch (raw_e) {
      let e = Primitive_exceptions.internalToException(raw_e);
      console.log(e);
      return;
    }
  });
  return orderedGames;
}

function removeGame(gameKey) {
  return Database$1.remove(Database$1.ref(Database.database, "games/" + gameKey));
}

export {
  addGame,
  getTimePeriod,
  fetchAllGames,
  removeGame,
  useLastGames,
}
/* modifierSchema Not a pure module */
