// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Database from "./Database.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";
import * as S$RescriptSchema from "rescript-schema/src/S.bs.mjs";
import * as Database$1 from "firebase/database";

var modifierSchema = S$RescriptSchema.union([
      S$RescriptSchema.object(function (s) {
            s.t("kind", "handicap");
            return {
                    TAG: "Handicap",
                    _0: s.f("blue", S$RescriptSchema.$$int),
                    _1: s.f("red", S$RescriptSchema.$$int)
                  };
          }),
      S$RescriptSchema.object(function (s) {
            s.t("kind", "one-v-one");
            return "OneVOne";
          })
    ]);

var gameSchema = S$RescriptSchema.object(function (s) {
      return {
              blueScore: s.f("blueScore", S$RescriptSchema.Int.min(S$RescriptSchema.$$int, 0, undefined)),
              redScore: s.f("redScore", S$RescriptSchema.Int.min(S$RescriptSchema.$$int, 0, undefined)),
              blueTeam: s.f("blueTeam", S$RescriptSchema.array(S$RescriptSchema.string)),
              redTeam: s.f("redTeam", S$RescriptSchema.array(S$RescriptSchema.string)),
              date: s.f("date", S$RescriptSchema.transform(S$RescriptSchema.$$float, (function (param) {
                          return {
                                  p: (function (prim) {
                                      return new Date(prim);
                                    }),
                                  s: (function (prim) {
                                      return prim.getTime();
                                    })
                                };
                        }))),
              modifiers: s.f("modifiers", S$RescriptSchema.array(modifierSchema))
            };
    });

async function addGame(game) {
  var gamesRef = Database$1.ref(Database.database, "games");
  var data = S$RescriptSchema.serializeWith(game, gameSchema);
  if (data.TAG === "Ok") {
    return Database$1.push(gamesRef, data._0);
  } else {
    return RescriptCore.panic("Could not create game");
  }
}

export {
  modifierSchema ,
  gameSchema ,
  addGame ,
}
/* modifierSchema Not a pure module */
