// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as OpenSkill from "./OpenSkill.bs.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.mjs";

function getOpenSkillRating(player) {
  return OpenSkill.createRating(player.mu, player.sigma, undefined);
}

function calculateOrdinal(mu, sigma) {
  return mu - 3.0 * sigma;
}

function teamToRatings(team) {
  return team.map(getOpenSkillRating);
}

function updatePlayerRating(player, newRating, dampeningOpt, param) {
  var dampening = dampeningOpt !== undefined ? dampeningOpt : 1.0;
  var newOrdinal = newRating.mu - 3.0 * newRating.sigma;
  var rawDelta = newOrdinal - player.ordinal;
  var dampenedDelta = rawDelta * dampening;
  var dampenedMu = player.mu + (newRating.mu - player.mu) * dampening;
  var dampenedSigma = player.sigma + (newRating.sigma - player.sigma) * dampening;
  var dampenedOrdinal = player.ordinal + dampenedDelta;
  var newrecord = Caml_obj.obj_dup(player);
  newrecord.lastOpenSkillChange = dampenedDelta;
  newrecord.ordinal = dampenedOrdinal;
  newrecord.sigma = dampenedSigma;
  newrecord.mu = dampenedMu;
  return newrecord;
}

function toDisplayOrdinal(ordinal) {
  return Math.round(ordinal * 60.0) | 0;
}

function toDisplayDelta(delta) {
  return Math.round(delta * 60.0) | 0;
}

function calculateScore(winners, losers, gameModeOpt) {
  var winnerRatings = winners.map(getOpenSkillRating);
  var loserRatings = losers.map(getOpenSkillRating);
  var match = OpenSkill.rateGame(winnerRatings, loserRatings);
  var newLoserRatings = match[1];
  var newWinnerRatings = match[0];
  var dampeningFactor = OpenSkill.applyVarianceDampening(winnerRatings, loserRatings, 1.0);
  var updatedWinners = winners.map(function (player, index) {
        var newRating = newWinnerRatings[index];
        return updatePlayerRating(player, newRating, dampeningFactor, undefined);
      });
  var updatedLosers = losers.map(function (player, index) {
        var newRating = newLoserRatings[index];
        return updatePlayerRating(player, newRating, dampeningFactor, undefined);
      });
  var avgWinnerChange = Core__Array.reduce(updatedWinners, 0.0, (function (acc, player) {
          return acc + player.lastOpenSkillChange;
        })) / updatedWinners.length;
  return [
          updatedWinners,
          updatedLosers,
          avgWinnerChange
        ];
}

function getWinProbability(teamA, teamB) {
  var ratingsA = teamA.map(getOpenSkillRating);
  var ratingsB = teamB.map(getOpenSkillRating);
  return OpenSkill.getWinProbability(ratingsA, ratingsB);
}

function roundScore(score) {
  return Math.round(score) | 0;
}

export {
  getOpenSkillRating ,
  calculateOrdinal ,
  teamToRatings ,
  updatePlayerRating ,
  toDisplayOrdinal ,
  toDisplayDelta ,
  calculateScore ,
  getWinProbability ,
  roundScore ,
}
/* OpenSkill Not a pure module */
