// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Core__Int from "@rescript/core/src/Core__Int.bs.mjs";
import * as OpenSkill from "./OpenSkill.bs.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.mjs";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

function getOpenSkillRating(player, gameModeOpt) {
  var gameMode = gameModeOpt !== undefined ? gameModeOpt : "Foosball";
  switch (gameMode) {
    case "Foosball" :
    case "Darts" :
        break;
    case "Fifa" :
        return OpenSkill.createRating(player.fifaMu, player.fifaSigma, undefined);
    
  }
  return OpenSkill.createRating(player.mu, player.sigma, undefined);
}

function calculateOrdinal(mu, sigma) {
  return mu - 3.0 * sigma;
}

function teamToRatings(team, gameModeOpt) {
  var gameMode = gameModeOpt !== undefined ? gameModeOpt : "Foosball";
  return team.map(function (player) {
              var gameModeOpt = gameMode;
              switch (gameModeOpt) {
                case "Foosball" :
                case "Darts" :
                    break;
                case "Fifa" :
                    return OpenSkill.createRating(player.fifaMu, player.fifaSigma, undefined);
                
              }
              return OpenSkill.createRating(player.mu, player.sigma, undefined);
            });
}

function marginMultiplier(scoreDiff) {
  var diff = Core__Int.clamp(1, 7, PervasivesU.abs(scoreDiff));
  return 1.0 + (diff - 1.0) / 6.0 * 0.5;
}

function applyMargin(previous, next, multiplier) {
  return {
          mu: previous.mu + (next.mu - previous.mu) * multiplier,
          sigma: next.sigma
        };
}

function updatePlayerRating(player, newRating, gameModeOpt) {
  var gameMode = gameModeOpt !== undefined ? gameModeOpt : "Foosball";
  var newOrdinal = newRating.mu - 3.0 * newRating.sigma;
  switch (gameMode) {
    case "Foosball" :
    case "Darts" :
        break;
    case "Fifa" :
        var osDelta = newOrdinal - player.fifaOrdinal;
        var newrecord = Caml_obj.obj_dup(player);
        newrecord.fifaLastOpenSkillChange = osDelta;
        newrecord.fifaOrdinal = newOrdinal;
        newrecord.fifaSigma = newRating.sigma;
        newrecord.fifaMu = newRating.mu;
        return newrecord;
    
  }
  var osDelta$1 = newOrdinal - player.ordinal;
  var newrecord$1 = Caml_obj.obj_dup(player);
  newrecord$1.lastOpenSkillChange = osDelta$1;
  newrecord$1.ordinal = newOrdinal;
  newrecord$1.sigma = newRating.sigma;
  newrecord$1.mu = newRating.mu;
  return newrecord$1;
}

function toDisplayOrdinal(ordinal) {
  return 1500 + (Math.round(ordinal * 60.0) | 0) | 0;
}

function toDisplayDelta(delta) {
  return Math.round(delta * 60.0) | 0;
}

function calculateScore(winners, losers, scoreDiff, gameModeOpt) {
  var gameMode = gameModeOpt !== undefined ? gameModeOpt : "Foosball";
  if (winners.length === 0 || losers.length === 0) {
    return [
            winners,
            losers,
            0.0
          ];
  }
  var winnerRatings = teamToRatings(winners, gameMode);
  var loserRatings = teamToRatings(losers, gameMode);
  var match = OpenSkill.rateGame(winnerRatings, loserRatings);
  var newLoserRatings = match[1];
  var newWinnerRatings = match[0];
  var multiplier = marginMultiplier(scoreDiff);
  var updatedWinners = winners.map(function (player, index) {
        var newRating = applyMargin(winnerRatings[index], newWinnerRatings[index], multiplier);
        return updatePlayerRating(player, newRating, gameMode);
      });
  var updatedLosers = losers.map(function (player, index) {
        var newRating = applyMargin(loserRatings[index], newLoserRatings[index], multiplier);
        return updatePlayerRating(player, newRating, gameMode);
      });
  var avgWinnerChange;
  var exit = 0;
  switch (gameMode) {
    case "Foosball" :
    case "Darts" :
        exit = 1;
        break;
    case "Fifa" :
        avgWinnerChange = Core__Array.reduce(updatedWinners, 0.0, (function (acc, player) {
                return acc + player.fifaLastOpenSkillChange;
              })) / updatedWinners.length;
        break;
    
  }
  if (exit === 1) {
    avgWinnerChange = Core__Array.reduce(updatedWinners, 0.0, (function (acc, player) {
            return acc + player.lastOpenSkillChange;
          })) / updatedWinners.length;
  }
  return [
          updatedWinners,
          updatedLosers,
          avgWinnerChange
        ];
}

function getWinProbability(teamA, teamB) {
  var ratingsA = teamToRatings(teamA, undefined);
  var ratingsB = teamToRatings(teamB, undefined);
  return OpenSkill.getWinProbability(ratingsA, ratingsB);
}

function roundScore(score) {
  return Math.round(score) | 0;
}

export {
  getOpenSkillRating ,
  calculateOrdinal ,
  teamToRatings ,
  marginMultiplier ,
  applyMargin ,
  updatePlayerRating ,
  toDisplayOrdinal ,
  toDisplayDelta ,
  calculateScore ,
  getWinProbability ,
  roundScore ,
}
/* OpenSkill Not a pure module */
