// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Openskill from "openskill";
import * as Caml_int32 from "rescript/lib/es6/caml_int32.js";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";

function createRating(muOpt, sigmaOpt, param) {
  var mu = muOpt !== undefined ? muOpt : 25.0;
  var sigma = sigmaOpt !== undefined ? sigmaOpt : 8.333;
  return Openskill.rating({
              mu: mu,
              sigma: sigma
            });
}

function defaultRating() {
  return Openskill.rating();
}

function getOrdinal(rating) {
  return Openskill.ordinal(rating);
}

function padTeam(team, size) {
  var count = team.length;
  if (count === 0 || count >= size) {
    return team;
  } else {
    return Core__Array.fromInitializer(size, (function (index) {
                  return team[Caml_int32.mod_(index, count)];
                }));
  }
}

function balanceTeams(teamA, teamB) {
  var size = teamA.length > teamB.length ? teamA.length : teamB.length;
  return [
          padTeam(teamA, size),
          padTeam(teamB, size)
        ];
}

function rateGame(winningTeam, losingTeam) {
  var winnerCount = winningTeam.length;
  var loserCount = losingTeam.length;
  var match = balanceTeams(winningTeam, losingTeam);
  var match$1 = Openskill.rate([
        match[0],
        match[1]
      ]);
  if (match$1.length !== 2) {
    return RescriptCore.panic("Unexpected result from rate function");
  }
  var winnerUpdates = match$1[0];
  var loserUpdates = match$1[1];
  return [
          winnerUpdates.slice(0, winnerCount),
          loserUpdates.slice(0, loserCount)
        ];
}

function getWinProbability(teamA, teamB) {
  var match = balanceTeams(teamA, teamB);
  var probabilities = Openskill.predictWin([
        match[0],
        match[1]
      ]);
  return probabilities[0];
}

function playerToRating(player) {
  var sigmaOpt = player.sigma;
  var muOpt = player.mu;
  return Openskill.rating({
              mu: muOpt,
              sigma: sigmaOpt
            });
}

export {
  createRating ,
  defaultRating ,
  getOrdinal ,
  padTeam ,
  balanceTeams ,
  rateGame ,
  getWinProbability ,
  playerToRating ,
}
/* openskill Not a pure module */
