// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OpenSkill from "./OpenSkill.bs.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.mjs";

function getOpenSkillRating(player) {
  return OpenSkill.createRating(player.mu, player.sigma, undefined);
}

function calculateOrdinal(mu, sigma) {
  return mu - 3.0 * sigma;
}

function teamToRatings(team) {
  return team.map(getOpenSkillRating);
}

function updatePlayerRating(player, newRating) {
  let newOrdinal = newRating.mu - 3.0 * newRating.sigma;
  let osDelta = newOrdinal - player.ordinal;
  let newrecord = {...player};
  newrecord.lastOpenSkillChange = osDelta;
  newrecord.ordinal = newOrdinal;
  newrecord.sigma = newRating.sigma;
  newrecord.mu = newRating.mu;
  return newrecord;
}

function toDisplayOrdinal(ordinal) {
  return Math.round(ordinal * 60.0) | 0;
}

function toDisplayDelta(delta) {
  return Math.round(delta * 60.0) | 0;
}

function calculateScore(winners, losers, gameModeOpt) {
  let winnerRatings = winners.map(getOpenSkillRating);
  let loserRatings = losers.map(getOpenSkillRating);
  let match = OpenSkill.rateGame(winnerRatings, loserRatings);
  let newLoserRatings = match[1];
  let newWinnerRatings = match[0];
  let updatedWinners = winners.map((player, index) => {
    let newRating = newWinnerRatings[index];
    return updatePlayerRating(player, newRating);
  });
  let updatedLosers = losers.map((player, index) => {
    let newRating = newLoserRatings[index];
    return updatePlayerRating(player, newRating);
  });
  let avgWinnerChange = Core__Array.reduce(updatedWinners, 0.0, (acc, player) => acc + player.lastOpenSkillChange) / updatedWinners.length;
  return [
    updatedWinners,
    updatedLosers,
    avgWinnerChange
  ];
}

function getWinProbability(teamA, teamB) {
  let ratingsA = teamA.map(getOpenSkillRating);
  let ratingsB = teamB.map(getOpenSkillRating);
  return OpenSkill.getWinProbability(ratingsA, ratingsB);
}

function roundScore(score) {
  return Math.round(score) | 0;
}

export {
  getOpenSkillRating,
  calculateOrdinal,
  teamToRatings,
  updatePlayerRating,
  toDisplayOrdinal,
  toDisplayDelta,
  calculateScore,
  getWinProbability,
  roundScore,
}
/* OpenSkill Not a pure module */
