// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Openskill from "openskill";
import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";

function createRating(muOpt, sigmaOpt, param) {
  let mu = muOpt !== undefined ? muOpt : 25.0;
  let sigma = sigmaOpt !== undefined ? sigmaOpt : 8.333;
  return Openskill.rating({
    mu: mu,
    sigma: sigma
  });
}

function defaultRating() {
  return Openskill.rating();
}

function getOrdinal(rating) {
  return Openskill.ordinal(rating);
}

function rateGame(winningTeam, losingTeam) {
  let teams = [
    winningTeam,
    losingTeam
  ];
  let results = Openskill.rate(teams, {
    balance: true
  });
  if (results.length !== 2) {
    return RescriptCore.panic("Unexpected result from rate function");
  }
  let winnerUpdates = results[0];
  let loserUpdates = results[1];
  return [
    winnerUpdates,
    loserUpdates
  ];
}

function getWinProbability(teamA, teamB) {
  let probabilities = Openskill.predictWin([
    teamA,
    teamB
  ]);
  return probabilities[0];
}

function playerToRating(player) {
  let sigmaOpt = player.sigma;
  let muOpt = player.mu;
  return Openskill.rating({
    mu: muOpt,
    sigma: sigmaOpt
  });
}

function getTeamAverageRating(team) {
  let totalMu = Core__Array.reduce(team, 0.0, (acc, rating) => acc + rating.mu);
  let totalSigma = Core__Array.reduce(team, 0.0, (acc, rating) => acc + rating.sigma);
  let teamSize = team.length;
  if (teamSize <= 0.0) {
    return Openskill.rating();
  }
  let sigmaOpt = totalSigma / teamSize;
  let muOpt = totalMu / teamSize;
  return Openskill.rating({
    mu: muOpt,
    sigma: sigmaOpt
  });
}

function applyMarginMultiplier(scoreA, scoreB, baseChange) {
  let scoreDiff = Pervasives.abs(scoreA - scoreB | 0);
  let margin = Math.max(1.0, scoreDiff * 0.5);
  return baseChange * margin;
}

export {
  createRating,
  defaultRating,
  getOrdinal,
  rateGame,
  getWinProbability,
  playerToRating,
  getTeamAverageRating,
  applyMarginMultiplier,
}
/* openskill Not a pure module */
