// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Schema from "./Schema.bs.mjs";
import * as Database from "./Database.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";
import * as Database$1 from "firebase/database";

let queuePlayerSchema = Schema.object(s => ({
  playerKey: s.f("playerKey", Schema.string),
  until: s.f("until", Schema.float)
}));

let queueSchema = Schema.object(s => ({
  players: s.f("players", Schema.array(queuePlayerSchema))
}));

async function enqueuePlayer(playerKey, until) {
  let playersRef = Database$1.ref(Database.database, "queue");
  let data;
  try {
    data = Schema.convertToJsonOrThrow({
      playerKey: playerKey,
      until: until
    }, queuePlayerSchema);
  } catch (exn) {
    data = RescriptCore.panic("Could not serialize queue player");
  }
  return await Database$1.push(playersRef, data);
}

export {
  queuePlayerSchema,
  queueSchema,
  enqueuePlayer,
}
/* queuePlayerSchema Not a pure module */
