// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pervasives from "@rescript/runtime/lib/es6/Pervasives.js";

function isRedWin(redScore, blueScore) {
  return redScore > blueScore;
}

function isBlueWin(redScore, blueScore) {
  return blueScore > redScore;
}

function isTue(redScore, blueScore) {
  return redScore === blueScore;
}

function isAbsolute(redScore, blueScore) {
  return Pervasives.abs(redScore - blueScore | 0) === 7;
}

export {
  isRedWin,
  isBlueWin,
  isTue,
  isAbsolute,
}
/* No side effect */
