// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";

function isRedWin(redScore, blueScore) {
  return redScore > blueScore;
}

function isBlueWin(redScore, blueScore) {
  return blueScore > redScore;
}

function isTue(redScore, blueScore) {
  return redScore === blueScore;
}

function isAbsolute(redScore, blueScore) {
  return PervasivesU.abs(redScore - blueScore | 0) === 7;
}

export {
  isRedWin ,
  isBlueWin ,
  isTue ,
  isAbsolute ,
}
/* No side effect */
