// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S$RescriptSchema from "rescript-schema/src/S.bs.mjs";

let Path = S$RescriptSchema.Path;

let Raised = S$RescriptSchema.Raised;

let Flag = S$RescriptSchema.Flag;

let $$Error = S$RescriptSchema.$$Error;

let Literal = S$RescriptSchema.Literal;

let never = S$RescriptSchema.never;

let unknown = S$RescriptSchema.unknown;

let unit = S$RescriptSchema.unit;

let string = S$RescriptSchema.string;

let bool = S$RescriptSchema.bool;

let int = S$RescriptSchema.int;

let float = S$RescriptSchema.float;

let bigint = S$RescriptSchema.bigint;

let json = S$RescriptSchema.json;

let literal = S$RescriptSchema.literal;

let array = S$RescriptSchema.array;

let unnest = S$RescriptSchema.unnest;

let list = S$RescriptSchema.list;

let dict = S$RescriptSchema.dict;

let option = S$RescriptSchema.option;

let $$null = S$RescriptSchema.$$null;

let nullable = S$RescriptSchema.nullable;

let jsonString = S$RescriptSchema.jsonString;

let union = S$RescriptSchema.union;

let $$enum = S$RescriptSchema.$$enum;

let Catch = S$RescriptSchema.Catch;

let $$catch = S$RescriptSchema.$$catch;

let describe = S$RescriptSchema.describe;

let description = S$RescriptSchema.description;

let deprecate = S$RescriptSchema.deprecate;

let deprecation = S$RescriptSchema.deprecation;

let transform = S$RescriptSchema.transform;

let preprocess = S$RescriptSchema.preprocess;

let custom = S$RescriptSchema.custom;

let refine = S$RescriptSchema.refine;

let to = S$RescriptSchema.to;

let shape = S$RescriptSchema.shape;

let coerce = S$RescriptSchema.coerce;

let compile = S$RescriptSchema.compile;

let parseOrThrow = S$RescriptSchema.parseOrThrow;

let parseJsonOrThrow = S$RescriptSchema.parseJsonOrThrow;

let parseJsonStringOrThrow = S$RescriptSchema.parseJsonStringOrThrow;

let parseAsyncOrThrow = S$RescriptSchema.parseAsyncOrThrow;

let convertOrThrow = S$RescriptSchema.convertOrThrow;

let convertToJsonOrThrow = S$RescriptSchema.convertToJsonOrThrow;

let convertToJsonStringOrThrow = S$RescriptSchema.convertToJsonStringOrThrow;

let convertAsyncOrThrow = S$RescriptSchema.convertAsyncOrThrow;

let reverseConvertOrThrow = S$RescriptSchema.reverseConvertOrThrow;

let reverseConvertToJsonOrThrow = S$RescriptSchema.reverseConvertToJsonOrThrow;

let reverseConvertToJsonStringOrThrow = S$RescriptSchema.reverseConvertToJsonStringOrThrow;

let assertOrThrow = S$RescriptSchema.assertOrThrow;

let isAsync = S$RescriptSchema.isAsync;

let recursive = S$RescriptSchema.recursive;

let setName = S$RescriptSchema.setName;

let removeTypeValidation = S$RescriptSchema.removeTypeValidation;

let Schema = S$RescriptSchema.Schema;

let schema = S$RescriptSchema.schema;

let $$Object = S$RescriptSchema.$$Object;

let object = S$RescriptSchema.object;

let strip = S$RescriptSchema.strip;

let deepStrip = S$RescriptSchema.deepStrip;

let strict = S$RescriptSchema.strict;

let deepStrict = S$RescriptSchema.deepStrict;

let Tuple = S$RescriptSchema.Tuple;

let tuple = S$RescriptSchema.tuple;

let tuple1 = S$RescriptSchema.tuple1;

let tuple2 = S$RescriptSchema.tuple2;

let tuple3 = S$RescriptSchema.tuple3;

let Option = S$RescriptSchema.Option;

let $$String = S$RescriptSchema.$$String;

let Int = S$RescriptSchema.Int;

let Float = S$RescriptSchema.Float;

let $$Array = S$RescriptSchema.$$Array;

let Metadata = S$RescriptSchema.Metadata;

let inline = S$RescriptSchema.inline;

let reverse = S$RescriptSchema.reverse;

let intMin = S$RescriptSchema.intMin;

let intMax = S$RescriptSchema.intMax;

let port = S$RescriptSchema.port;

let floatMin = S$RescriptSchema.floatMin;

let floatMax = S$RescriptSchema.floatMax;

let arrayMinLength = S$RescriptSchema.arrayMinLength;

let arrayMaxLength = S$RescriptSchema.arrayMaxLength;

let arrayLength = S$RescriptSchema.arrayLength;

let stringMinLength = S$RescriptSchema.stringMinLength;

let stringMaxLength = S$RescriptSchema.stringMaxLength;

let stringLength = S$RescriptSchema.stringLength;

let email = S$RescriptSchema.email;

let uuid = S$RescriptSchema.uuid;

let cuid = S$RescriptSchema.cuid;

let url = S$RescriptSchema.url;

let pattern = S$RescriptSchema.pattern;

let datetime = S$RescriptSchema.datetime;

let trim = S$RescriptSchema.trim;

let setGlobalConfig = S$RescriptSchema.setGlobalConfig;

export {
  Path,
  Raised,
  Flag,
  $$Error,
  Literal,
  never,
  unknown,
  unit,
  string,
  bool,
  int,
  float,
  bigint,
  json,
  literal,
  array,
  unnest,
  list,
  dict,
  option,
  $$null,
  nullable,
  jsonString,
  union,
  $$enum,
  Catch,
  $$catch,
  describe,
  description,
  deprecate,
  deprecation,
  transform,
  preprocess,
  custom,
  refine,
  to,
  shape,
  coerce,
  compile,
  parseOrThrow,
  parseJsonOrThrow,
  parseJsonStringOrThrow,
  parseAsyncOrThrow,
  convertOrThrow,
  convertToJsonOrThrow,
  convertToJsonStringOrThrow,
  convertAsyncOrThrow,
  reverseConvertOrThrow,
  reverseConvertToJsonOrThrow,
  reverseConvertToJsonStringOrThrow,
  assertOrThrow,
  isAsync,
  recursive,
  setName,
  removeTypeValidation,
  Schema,
  schema,
  $$Object,
  object,
  strip,
  deepStrip,
  strict,
  deepStrict,
  Tuple,
  tuple,
  tuple1,
  tuple2,
  tuple3,
  Option,
  $$String,
  Int,
  Float,
  $$Array,
  Metadata,
  inline,
  reverse,
  intMin,
  intMax,
  port,
  floatMin,
  floatMax,
  arrayMinLength,
  arrayMaxLength,
  arrayLength,
  stringMinLength,
  stringMaxLength,
  stringLength,
  email,
  uuid,
  cuid,
  url,
  pattern,
  datetime,
  trim,
  setGlobalConfig,
}
/* S-RescriptSchema Not a pure module */
