// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Games from "./Games.bs.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Players from "./Players.bs.mjs";
import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";

async function getDailyOverview(period) {
  var periodEnum;
  switch (period) {
    case "All" :
        periodEnum = "All";
        break;
    case "Monthly" :
        periodEnum = "Monthly";
        break;
    case "Weekly" :
        periodEnum = "Weekly";
        break;
    default:
      periodEnum = "Daily";
  }
  var games = await Games.getTimePeriod(periodEnum);
  var players = await Players.fetchAllPlayers();
  var creepsMap = new Map();
  Object.values(games).forEach(function (game) {
        var winner = game.blueScore > game.redScore ? "Blue" : "Red";
        var absGoalDiff = PervasivesU.abs(game.blueScore - game.redScore | 0);
        var deltas = Core__Option.getExn(game.scoreDeltas, undefined);
        Js_dict.entries(deltas).forEach(function (param) {
              var scoreDelta = param[1];
              var playerKey = param[0];
              var player = Core__Option.getExn(players[playerKey], undefined);
              var lost = game.blueTeam.includes(playerKey) ? winner === "Red" : winner === "Blue";
              var goalDiffDelta = game.blueTeam.includes(playerKey) ? (
                  winner === "Red" ? -absGoalDiff | 0 : absGoalDiff
                ) : (
                  winner === "Blue" ? -absGoalDiff | 0 : absGoalDiff
                );
              var match = Core__Option.getOr(creepsMap.get(playerKey), {
                    name: player.name,
                    creeps: 0,
                    games: 0,
                    score: 0,
                    goalDiff: 0
                  });
              var goalDiff = match.goalDiff;
              var score = match.score;
              var games = match.games;
              var creeps = match.creeps;
              var match$1 = lost ? [
                  creeps + 1 | 0,
                  games + 1 | 0,
                  score + scoreDelta | 0,
                  goalDiff + goalDiffDelta | 0
                ] : [
                  creeps + 0 | 0,
                  games + 1 | 0,
                  score + scoreDelta | 0,
                  goalDiff + goalDiffDelta | 0
                ];
              creepsMap.set(playerKey, {
                    name: player.name,
                    creeps: match$1[0],
                    games: match$1[1],
                    score: match$1[2],
                    goalDiff: match$1[3]
                  });
            });
      });
  return creepsMap;
}

function toAPIObject(data) {
  return Object.fromEntries(data.entries());
}

export {
  getDailyOverview ,
  toAPIObject ,
}
/* Games Not a pure module */
