// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "../components/Button.bs.mjs";
import * as Players from "../helpers/Players.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function mapPlayer(users, key) {
  var creeper = Players.playerByKey(users, key);
  if (creeper !== undefined) {
    return creeper.name;
  } else {
    return "...";
  }
}

function ConfirmationStep(props) {
  var players = props.players;
  var reset = props.reset;
  var winners = props.winners.map(function (winner) {
        return mapPlayer(players, winner);
      });
  var winnerNames = winners.join(" & ");
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Gefeliciteerd, " + winnerNames + "!",
                      className: "text-3xl"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        "+",
                        props.score
                      ],
                      className: "text-lime-400 text-[160px]",
                      style: {
                        textShadow: "0 0 20px rgb(163 230 53)"
                      }
                    }),
                JsxRuntime.jsx(Button.make, {
                      variant: "Blue",
                      onClick: (function (param) {
                          reset();
                        }),
                      children: "Verder"
                    })
              ],
              className: "flex justify-center items-center h-screen flex-col"
            });
}

var make = ConfirmationStep;

export {
  mapPlayer ,
  make ,
}
/* Button Not a pure module */
