// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logger from "./Logger.bs.mjs";
import * as Schema from "../helpers/Schema.bs.mjs";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Players from "../helpers/Players.bs.mjs";
import * as Database from "../helpers/Database.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

async function make(param) {
  let players = await fetch(Database.databaseURL + `/` + Players.bucket + `.json`, {
    method: "GET"
  });
  let players$1;
  try {
    players$1 = Js_dict.values(Schema.parseOrThrow(await players.json(), Players.playersSchema)).toReversed().toSorted((a, b) => b.games - a.games | 0);
  } catch (exn) {
    players$1 = [];
  }
  return JsxRuntime.jsx(JsxRuntime.Fragment, {
    children: JsxRuntime.jsx(Logger.make, {
      players: players$1
    })
  });
}

let LoggerS = make;

let make$1 = LoggerS;

export {
  make$1 as make,
}
/* Logger Not a pure module */
