// Generated by ReScript, PLEASE EDIT WITH CARE


function getNextStep(step) {
  switch (step) {
    case "UserSelection" :
        return "ScoreForm";
    case "ScoreForm" :
        return "Confirmation";
    case "Confirmation" :
        return "UserSelection";
    
  }
}

export {
  getNextStep ,
}
/* No side effect */
