// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cn from "rescript-classnames/src/Cn.bs.mjs";
import * as Header from "./Header.bs.mjs";
import * as Players from "../helpers/Players.bs.mjs";
import * as GridItem from "./GridItem.bs.mjs";
import * as LoggerStep from "./LoggerStep.bs.mjs";
import * as NewPlayerForm from "./NewPlayerForm.bs.mjs";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as UserGridModuleCss from "./user-grid.module.css";

var styles = UserGridModuleCss;

function mapPlayer(players, key) {
  var player = Players.playerByKey(players, key);
  if (player !== undefined) {
    return JsxRuntime.jsx("li", {
                children: player.name
              });
  } else {
    return JsxRuntime.jsx("li", {
                children: "..."
              });
  }
}

function UserGrid(props) {
  var setStep = props.setStep;
  var setSelectedUsers = props.setSelectedUsers;
  var selectedUsers = props.selectedUsers;
  var players = props.players.map(function (item) {
        var match = Belt_MapString.get(selectedUsers, item.key);
        var tmp;
        tmp = match !== undefined ? (
            match === "Blue" ? styles.blueTeamGridItem : styles.redTeamGridItem
          ) : "noTeam";
        return JsxRuntime.jsxs(GridItem.make, {
                    active: Belt_MapString.has(selectedUsers, item.key),
                    children: [
                      JsxRuntime.jsx("button", {
                            children: JsxRuntime.jsx("b", {
                                  children: item.name,
                                  className: styles.creepsName
                                }),
                            className: styles.button,
                            onClick: (function (param) {
                                setSelectedUsers(function (s) {
                                      return Belt_MapString.remove(s, item.key);
                                    });
                              })
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: "Blauw",
                                    className: styles.buttonBlue,
                                    onClick: (function (param) {
                                        setSelectedUsers(function (s) {
                                              return Belt_MapString.set(s, item.key, "Blue");
                                            });
                                      })
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Rood",
                                    className: styles.buttonRed,
                                    onClick: (function (param) {
                                        setSelectedUsers(function (s) {
                                              return Belt_MapString.set(s, item.key, "Red");
                                            });
                                      })
                                  })
                            ],
                            className: styles.buttons
                          })
                    ],
                    className: Cn.make([
                          styles.gridItem,
                          tmp
                        ])
                  }, item.key);
      });
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Header.make, {
                      step: "ScoreForm",
                      onNextStep: (function () {
                          setStep(function (step) {
                                return LoggerStep.getNextStep(step);
                              });
                        }),
                      onReset: props.reset,
                      disabled: Belt_MapString.size(selectedUsers) <= 1
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        players,
                        JsxRuntime.jsx(GridItem.make, {
                              active: false,
                              children: JsxRuntime.jsx(NewPlayerForm.make, {})
                            }),
                        JsxRuntime.jsx("div", {
                              className: styles.gridSpacer
                            }),
                        JsxRuntime.jsx("div", {
                              className: styles.gridSpacer
                            }),
                        JsxRuntime.jsx("div", {
                              className: styles.gridSpacer
                            }),
                        JsxRuntime.jsx("div", {
                              className: styles.gridSpacer
                            }),
                        JsxRuntime.jsx("div", {
                              className: styles.gridSpacer
                            })
                      ],
                      className: styles.usersGrid
                    })
              ]
            });
}

var make = UserGrid;

export {
  styles ,
  mapPlayer ,
  make ,
}
/* styles Not a pure module */
