// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cn from "rescript-classnames/src/Cn.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ButtonModuleCss from "./button.module.css";

let styles = ButtonModuleCss;

function Button(props) {
  let __disabled = props.disabled;
  let __type_ = props.type_;
  let __className = props.className;
  let className = __className !== undefined ? __className : "";
  let type_ = __type_ !== undefined ? __type_ : "button";
  let disabled = __disabled !== undefined ? __disabled : false;
  let tmp;
  switch (props.variant) {
    case "Blue" :
      tmp = styles.buttonBlue;
      break;
    case "Grey" :
      tmp = styles.buttonGrey;
      break;
    case "Red" :
      tmp = styles.buttonRed;
      break;
  }
  return JsxRuntime.jsx("button", {
    children: props.children,
    className: Cn.make([
      styles.button,
      tmp,
      className
    ]),
    disabled: disabled,
    type: type_,
    onClick: props.onClick
  });
}

let make = Button;

export {
  make,
}
/* styles Not a pure module */
