// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.mjs";
import * as Js_dict from "@rescript/runtime/lib/es6/Js_dict.js";
import * as Players from "../helpers/Players.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function mapPlayer(users, key) {
  let creeper = Players.playerByKey(users, key);
  if (creeper !== undefined) {
    return creeper.name;
  } else {
    return "...";
  }
}

function ConfirmationStep(props) {
  let perPlayerDeltas = props.perPlayerDeltas;
  let players = props.players;
  let reset = props.reset;
  let winners = props.winners;
  let winnerNames = winners.map(winner => mapPlayer(players, winner)).join(" & ");
  let tmp;
  if (perPlayerDeltas !== undefined) {
    let items = winners.map(wKey => {
      let name = mapPlayer(players, wKey);
      let delta = Core__Option.getOr(Js_dict.get(perPlayerDeltas, wKey), 0);
      let sign = delta >= 0 ? "+" : "";
      return JsxRuntime.jsx("li", {
        children: name + ": " + sign + delta.toString()
      }, wKey);
    });
    tmp = JsxRuntime.jsx("ul", {
      children: items,
      className: "mb-6"
    });
  } else {
    tmp = null;
  }
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Gefeliciteerd, " + winnerNames + "!",
        className: "text-3xl"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          "+",
          props.score
        ],
        className: "text-lime-400 text-[160px]",
        style: {
          textShadow: "0 0 20px rgb(163 230 53)"
        }
      }),
      tmp,
      JsxRuntime.jsx(Button.make, {
        variant: "Blue",
        onClick: param => reset(),
        children: "Verder"
      })
    ],
    className: "flex justify-center items-center h-screen flex-col"
  });
}

let make = ConfirmationStep;

export {
  make,
}
/* Button Not a pure module */
