// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as JsxRuntime from "react/jsx-runtime";

function make(props) {
  var newrecord = Caml_obj.obj_dup(props);
  return JsxRuntime.jsxs("svg", (newrecord.xmlns = "http://www.w3.org/2000/svg", newrecord.viewBox = "-0.5 -0.5 16 16", newrecord.width = "1em", newrecord.height = "1em", newrecord["aria-hidden"] = true, newrecord.children = [
                JsxRuntime.jsx("path", {
                      d: "M12.881 5A5.931 5.931 0 1 1 10 2.119",
                      fill: "none",
                      stroke: "currentColor",
                      strokeMiterlimit: "10"
                    }),
                JsxRuntime.jsx("path", {
                      d: "M10.263 6.412a2.875 2.875 0 0 1 .206 1.088A2.969 2.969 0 1 1 7.5 4.531a2.875 2.875 0 0 1 1.087.207",
                      fill: "none",
                      stroke: "currentColor",
                      strokeMiterlimit: "10"
                    }),
                JsxRuntime.jsx("path", {
                      d: "m7.5 7.5 3.563-3.563V2.75l1.187-1.188V2.75h1.188L12.25 3.938h-1.188",
                      fill: "none",
                      stroke: "currentColor",
                      strokeMiterlimit: "10"
                    }),
                JsxRuntime.jsx("path", {
                      d: "M6.906 7.5a.594.594 0 1 0 1.188 0 .594.594 0 1 0-1.188 0",
                      fill: "none",
                      stroke: "currentColor",
                      strokeMiterlimit: "10"
                    })
              ], newrecord));
}

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
