// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Elo from "../helpers/Elo.bs.mjs";
import * as Stats from "../helpers/Stats.bs.mjs";
import * as React from "react";
import * as Button from "./Button.bs.mjs";
import * as Header from "./Header.bs.mjs";
import * as Players from "../helpers/Players.bs.mjs";
import * as DartsGames from "../helpers/DartsGames.bs.mjs";
import * as LoggerStep from "../helpers/LoggerStep.bs.mjs";
import * as Mattermost from "../helpers/Mattermost.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

let modes = [
  "M301",
  "M501",
  "Bullen",
  "Killer",
  "AroundTheClock"
];

function DartsGameModeStep(props) {
  let players = props.players;
  let setEarnedPoints = props.setEarnedPoints;
  let setStep = props.setStep;
  let selectedUsers = props.selectedUsers;
  let match = React.useState(() => {});
  let setDartMode = match[1];
  let dartMode = match[0];
  let match$1 = React.useState(() => false);
  let setIsSaving = match$1[1];
  let modeButtons = modes.map(mode => JsxRuntime.jsx(Button.make, {
    className: "w-[300px]",
    variant: Primitive_object.equal(dartMode, mode) ? "Blue" : "Grey",
    onClick: param => setDartMode(param => mode),
    children: DartsGames.dartsModeToString(mode)
  }, DartsGames.dartsModeToString(mode)));
  let mapUser = extra => {
    let player = Players.playerByKey(players, extra);
    if (player !== undefined) {
      return JsxRuntime.jsx("li", {
        children: player.name
      }, extra);
    } else {
      return JsxRuntime.jsx("li", {
        children: "..."
      }, extra);
    }
  };
  let selectedBlueUsers = Belt_MapString.keysToArray(Belt_MapString.keep(selectedUsers, (param, value) => value === "Blue"));
  let selectedRedUsers = Belt_MapString.keysToArray(Belt_MapString.keep(selectedUsers, (param, value) => value === "Red"));
  let blueUsers = selectedBlueUsers.map(mapUser);
  let redUsers = selectedRedUsers.map(mapUser);
  let redPlayers = selectedRedUsers.map(key => Core__Option.getExn(Players.playerByKey(players, key), undefined));
  let bluePlayers = selectedBlueUsers.map(key => Core__Option.getExn(Players.playerByKey(players, key), undefined));
  let sendUpdate = (extra, extra$1) => Mattermost.sendDartsUpdate(bluePlayers, redPlayers, extra, extra$1);
  let saveGame = async () => {
    setIsSaving(param => true);
    await DartsGames.addDartsGame({
      winners: selectedBlueUsers,
      losers: selectedRedUsers,
      date: new Date(),
      mode: Core__Option.getExn(dartMode, undefined)
    });
    let bluePlayers = selectedBlueUsers.map(key => Core__Option.getExn(Players.playerByKey(players, key), undefined));
    let redPlayers = selectedRedUsers.map(key => Core__Option.getExn(Players.playerByKey(players, key), undefined));
    let match = Elo.calculateScore(bluePlayers, redPlayers, "Darts");
    let roundedPoints = Elo.roundScore(match[2]);
    setEarnedPoints(param => roundedPoints);
    await Promise.all(match[0].map(async player => Players.updateDartsGameStats(player.key, 1, player.dartsElo)));
    await Promise.all(match[1].map(async player => Players.updateDartsGameStats(player.key, 0, player.dartsElo)));
    await Stats.updateDartsStats();
    await sendUpdate(roundedPoints, DartsGames.dartsModeToString(Core__Option.getOr(dartMode, "Unknown")));
    setIsSaving(param => false);
    return setStep(LoggerStep.getNextStep);
  };
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx(Header.make, {
        step: "ScoreForm",
        onNextStep: () => {
          saveGame();
        },
        onReset: props.reset,
        disabled: match$1[0] || Core__Option.isNone(dartMode),
        setShowQueueButtons: param => {},
        gameMode: props.gameMode,
        setGameMode: undefined,
        searchQuery: undefined,
        setSearchQuery: undefined,
        setSelectedUsers: undefined,
        onMatchFound: undefined
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Gamemode",
                className: "font-bold text-3xl"
              }),
              JsxRuntime.jsx("div", {
                children: modeButtons,
                className: "flex flex-col gap-4 pt-4"
              })
            ]
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Winner",
                className: "font-bold text-3xl"
              }),
              JsxRuntime.jsx("ol", {
                children: blueUsers,
                className: "pl-5 pt-4 pb-8 list-decimal text-2xl"
              })
            ]
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("h2", {
                children: "Loser",
                className: "font-bold text-3xl"
              }),
              JsxRuntime.jsx("ol", {
                children: redUsers,
                className: "pl-5 pt-4 pb-8 list-decimal text-2xl"
              })
            ]
          })
        ],
        className: "flex flex-wrap content-padding gap-20"
      })
    ]
  });
}

let make = DartsGameModeStep;

export {
  make,
}
/* Stats Not a pure module */
