// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Header from "./Header.bs.mjs";
import * as Players from "../helpers/Players.bs.mjs";
import * as Core__Int from "@rescript/core/src/Core__Int.bs.mjs";
import * as FifaGames from "../helpers/FifaGames.bs.mjs";
import * as LoggerStep from "../helpers/LoggerStep.bs.mjs";
import * as Mattermost from "../helpers/Mattermost.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as RescriptCore from "@rescript/core/src/RescriptCore.bs.mjs";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as OpenSkillRating from "../helpers/OpenSkillRating.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function mapUser(players, key) {
  var player = Players.playerByKey(players, key);
  if (player !== undefined) {
    return JsxRuntime.jsx("li", {
                children: player.name
              }, key);
  } else {
    return JsxRuntime.jsx("li", {
                children: "..."
              }, key);
  }
}

function FifaScoreStep(props) {
  var players = props.players;
  var setEarnedPoints = props.setEarnedPoints;
  var setStep = props.setStep;
  var selectedUsers = props.selectedUsers;
  var match = React.useState(function () {
        return false;
      });
  var setIsSaving = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setBlueScore = match$1[1];
  var blueScore = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setRedScore = match$2[1];
  var redScore = match$2[0];
  var mapUser$1 = function (extra) {
    return mapUser(players, extra);
  };
  var selectedBlueUsers = Belt_MapString.keysToArray(Belt_MapString.keep(selectedUsers, (function (param, value) {
              return value === "Blue";
            })));
  var selectedRedUsers = Belt_MapString.keysToArray(Belt_MapString.keep(selectedUsers, (function (param, value) {
              return value === "Red";
            })));
  var blueUsers = selectedBlueUsers.map(mapUser$1);
  var redUsers = selectedRedUsers.map(mapUser$1);
  var redPlayers = selectedRedUsers.map(function (key) {
        return Core__Option.getExn(Players.playerByKey(players, key), undefined);
      });
  var bluePlayers = selectedBlueUsers.map(function (key) {
        return Core__Option.getExn(Players.playerByKey(players, key), undefined);
      });
  var sendUpdate = function (extra, extra$1) {
    return Mattermost.sendFifaUpdate(bluePlayers, redPlayers, extra, extra$1);
  };
  var blueScoreInt = Core__Option.getOr(Core__Int.fromString(blueScore, undefined), 0);
  var redScoreInt = Core__Option.getOr(Core__Int.fromString(redScore, undefined), 0);
  var saveGame = async function () {
    setIsSaving(function (param) {
          return true;
        });
    await FifaGames.addFifaGame({
          blueScore: blueScoreInt,
          redScore: redScoreInt,
          blueTeam: selectedBlueUsers,
          redTeam: selectedRedUsers,
          date: new Date()
        });
    var winningTeam = blueScoreInt > redScoreInt ? "Blue" : (
        redScoreInt > blueScoreInt ? "Red" : RescriptCore.panic("Tie not implemented for FIFA")
      );
    var match;
    if (winningTeam === "Blue") {
      match = OpenSkillRating.calculateScore(bluePlayers, redPlayers, "Fifa");
    } else {
      var match$1 = OpenSkillRating.calculateScore(redPlayers, bluePlayers, "Fifa");
      match = [
        match$1[1],
        match$1[0],
        match$1[2]
      ];
    }
    var osPoints = match[2];
    setEarnedPoints(function (param) {
          return osPoints;
        });
    await Promise.all(match[0].map(async function (player) {
                return Players.updateFifaGameStats(player.key, blueScoreInt, redScoreInt, player.fifaMu, player.fifaSigma, player.fifaOrdinal, player.fifaLastOpenSkillChange);
              }).concat(match[1].map(async function (player) {
                  return Players.updateFifaGameStats(player.key, redScoreInt, blueScoreInt, player.fifaMu, player.fifaSigma, player.fifaOrdinal, player.fifaLastOpenSkillChange);
                })));
    await sendUpdate(blueScoreInt, redScoreInt);
    setIsSaving(function (param) {
          return false;
        });
    return setStep(function (step) {
                return LoggerStep.getNextStep(step);
              });
  };
  var allScoresEntered = blueScore !== "" && redScore !== "";
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Header.make, {
                      step: "ScoreForm",
                      onNextStep: (function () {
                          saveGame();
                        }),
                      onReset: props.reset,
                      disabled: match[0] || !allScoresEntered,
                      setShowQueueButtons: (function (param) {
                          
                        }),
                      gameMode: props.gameMode
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: "Blauw",
                                      className: "font-bold text-3xl text-[#86b7ff]"
                                    }),
                                JsxRuntime.jsx("ol", {
                                      children: blueUsers,
                                      className: "pl-5 pt-4 pb-8 list-decimal text-2xl"
                                    }),
                                JsxRuntime.jsx("input", {
                                      className: "w-32 px-4 py-3 text-3xl text-white bg-white/10 rounded",
                                      min: "0",
                                      placeholder: "Score",
                                      type: "number",
                                      value: blueScore,
                                      onChange: (function (e) {
                                          var value = e.target.value;
                                          setBlueScore(function (param) {
                                                return value;
                                              });
                                        })
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: "Rood",
                                      className: "font-bold text-3xl text-[#ff8686]"
                                    }),
                                JsxRuntime.jsx("ol", {
                                      children: redUsers,
                                      className: "pl-5 pt-4 pb-8 list-decimal text-2xl"
                                    }),
                                JsxRuntime.jsx("input", {
                                      className: "w-32 px-4 py-3 text-3xl text-white bg-white/10 rounded",
                                      min: "0",
                                      placeholder: "Score",
                                      type: "number",
                                      value: redScore,
                                      onChange: (function (e) {
                                          var value = e.target.value;
                                          setRedScore(function (param) {
                                                return value;
                                              });
                                        })
                                    })
                              ]
                            })
                      ],
                      className: "flex flex-wrap content-padding gap-10"
                    })
              ]
            });
}

var make = FifaScoreStep;

export {
  mapUser ,
  make ,
}
/* react Not a pure module */
