// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stats from "../helpers/Stats.bs.mjs";
import * as React from "react";
import * as Button from "./Button.bs.mjs";
import * as Players from "../helpers/Players.bs.mjs";
import * as OpenSkill from "../helpers/OpenSkill.bs.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as OpenSkillRating from "../helpers/OpenSkillRating.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function MatchMakerModal(props) {
  let onMatchFound = props.onMatchFound;
  let setGameMode = props.setGameMode;
  let setSelectedUsers = props.setSelectedUsers;
  let setShow = props.setShow;
  let players = Players.useAllPlayers("rating", false);
  let stats = Stats.useStats();
  let match = React.useState(() => {});
  let setSelected = match[1];
  let selected = match[0];
  let toggleSelected = key => setSelected(s => {
    let match = Belt_MapString.get(s, key);
    if (match !== undefined && match) {
      return Belt_MapString.set(s, key, false);
    } else {
      return Belt_MapString.set(s, key, true);
    }
  });
  let getSelectedPlayers = () => {
    let keys = Belt_MapString.keysToArray(Belt_MapString.keep(selected, (param, v) => v === true));
    let opts = keys.map(key => Players.playerByKey(players, key));
    let filtered = opts.filter(Core__Option.isSome);
    return filtered.map(opt => Core__Option.getExn(opt, undefined));
  };
  let playerToRating = OpenSkill.playerToRating;
  let bestPairingOfFour = ps => {
    let p0 = ps[0];
    let p1 = ps[1];
    let p2 = ps[2];
    let p3 = ps[3];
    let teamA = [
      OpenSkill.playerToRating(p0),
      OpenSkill.playerToRating(p1)
    ];
    let teamB = [
      OpenSkill.playerToRating(p2),
      OpenSkill.playerToRating(p3)
    ];
    let p = OpenSkill.getWinProbability(teamA, teamB);
    let teamA$1 = [
      OpenSkill.playerToRating(p0),
      OpenSkill.playerToRating(p2)
    ];
    let teamB$1 = [
      OpenSkill.playerToRating(p1),
      OpenSkill.playerToRating(p3)
    ];
    let p$1 = OpenSkill.getWinProbability(teamA$1, teamB$1);
    let teamA$2 = [
      OpenSkill.playerToRating(p0),
      OpenSkill.playerToRating(p3)
    ];
    let teamB$2 = [
      OpenSkill.playerToRating(p1),
      OpenSkill.playerToRating(p2)
    ];
    let p$2 = OpenSkill.getWinProbability(teamA$2, teamB$2);
    let pairs = [
      [
        [
          [
            p0,
            p1
          ],
          [
            p2,
            p3
          ]
        ],
        Math.abs(p - 0.5)
      ],
      [
        [
          [
            p0,
            p2
          ],
          [
            p1,
            p3
          ]
        ],
        Math.abs(p$1 - 0.5)
      ],
      [
        [
          [
            p0,
            p3
          ],
          [
            p1,
            p2
          ]
        ],
        Math.abs(p$2 - 0.5)
      ]
    ];
    return Core__Array.reduce(pairs, pairs[0], (best, cur) => {
      if (cur[1] < best[1]) {
        return cur;
      } else {
        return best;
      }
    });
  };
  let chooseBestMatch = sel => {
    let n = sel.length;
    if (n < 4) {
      return;
    }
    if (n === 4) {
      let match = bestPairingOfFour(sel);
      let match$1 = match[0];
      return [
        match$1[0],
        match$1[1]
      ];
    }
    let best;
    for (let i = 0, i_finish = n - 4 | 0; i <= i_finish; ++i) {
      for (let j = i + 1 | 0, j_finish = n - 3 | 0; j <= j_finish; ++j) {
        for (let k = j + 1 | 0, k_finish = n - 2 | 0; k <= k_finish; ++k) {
          for (let l = k + 1 | 0; l < n; ++l) {
            let ps = [
              sel[i],
              sel[j],
              sel[k],
              sel[l]
            ];
            let match$2 = bestPairingOfFour(ps);
            let dev = match$2[1];
            let match$3 = match$2[0];
            let b = match$3[1];
            let a = match$3[0];
            let match$4 = best;
            best = match$4 !== undefined && dev >= match$4[1] ? best : [
                [
                  a,
                  b
                ],
                dev
              ];
          }
        }
      }
    }
    let match$5 = best;
    if (match$5 !== undefined) {
      return match$5[0];
    }
  };
  let assignColors = (teamA, teamB) => {
    let pA = OpenSkill.getWinProbability(teamA.map(playerToRating), teamB.map(playerToRating));
    let teamAIsStronger = pA >= 0.5;
    let total = stats.totalBlueWins + stats.totalRedWins | 0;
    let blueStronger = total > 0 ? stats.totalBlueWins / total > 0.5 : false;
    if (blueStronger) {
      if (teamAIsStronger) {
        return [
          teamB,
          teamA
        ];
      } else {
        return [
          teamA,
          teamB
        ];
      }
    } else if (teamAIsStronger) {
      return [
        teamA,
        teamB
      ];
    } else {
      return [
        teamB,
        teamA
      ];
    }
  };
  let makeMatch = () => {
    let selPlayers = getSelectedPlayers();
    let match = chooseBestMatch(selPlayers);
    if (match === undefined) {
      return;
    }
    let match$1 = assignColors(match[0], match[1]);
    let redTeam = match$1[1];
    let blueTeam = match$1[0];
    if (setSelectedUsers !== undefined) {
      setSelectedUsers(param => {
        let withBlue = Core__Array.reduce(blueTeam, undefined, (m, p) => Belt_MapString.set(m, p.key, "Blue"));
        return Core__Array.reduce(redTeam, withBlue, (m, p) => Belt_MapString.set(m, p.key, "Red"));
      });
    }
    if (setGameMode !== undefined) {
      setGameMode(param => "Foosball");
    }
    let pBlue = OpenSkill.getWinProbability(blueTeam.map(playerToRating), redTeam.map(playerToRating));
    if (onMatchFound !== undefined) {
      onMatchFound(blueTeam, redTeam, pBlue);
    }
    setSelected(param => {});
    setShow(s => !s);
  };
  let numSelected = Belt_MapString.size(Belt_MapString.keep(selected, (param, v) => v === true));
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("header", {
        children: [
          JsxRuntime.jsx(Button.make, {
            variant: "Blue",
            onClick: param => setShow(s => !s),
            children: "Terug"
          }),
          JsxRuntime.jsx("div", {
            className: "flex-1"
          }),
          JsxRuntime.jsx(Button.make, {
            variant: "Blue",
            onClick: param => makeMatch(),
            children: "Make a match",
            disabled: numSelected < 4
          })
        ],
        className: "flex items-center gap-4"
      }),
      JsxRuntime.jsx("h2", {
        children: "Select players (min 4)",
        className: "pt-5 mb-4 block text-2xl"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          "Selected: ",
          numSelected
        ],
        className: "text-white/70 mb-2"
      }),
      JsxRuntime.jsx("ul", {
        children: players.map(p => {
          let match = Belt_MapString.get(selected, p.key);
          let isSelected = match !== undefined ? match : false;
          return JsxRuntime.jsxs("li", {
            children: [
              JsxRuntime.jsxs("button", {
                children: [
                  JsxRuntime.jsx("strong", {
                    children: p.name
                  }),
                  JsxRuntime.jsx("span", {
                    children: OpenSkillRating.toDisplayOrdinal(p.ordinal).toString(),
                    className: "ml-2 text-white/60"
                  })
                ],
                className: "text-left flex-1",
                onClick: param => toggleSelected(p.key)
              }),
              JsxRuntime.jsx("input", {
                "aria-label": p.name,
                className: "w-5 h-5",
                checked: isSelected,
                type: "checkbox",
                onChange: param => toggleSelected(p.key)
              })
            ],
            className: "p-2 rounded border-white/20 border bg-white/5 flex justify-between items-center"
          }, p.key);
        }),
        className: "grid grid-cols-1 md:grid-cols-2 gap-2 overflow-auto"
      }),
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx(Button.make, {
          variant: "Grey",
          onClick: param => setSelected(param => {}),
          children: "Clear"
        }),
        className: "mt-4 flex gap-2"
      })
    ],
    className: "modal flex flex-col",
    style: {
      transform: props.show ? "translateX(0)" : "translateX(-100%)"
    }
  });
}

let make = MatchMakerModal;

export {
  make,
}
/* Stats Not a pure module */
