// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.bs.mjs";
import * as Players from "../helpers/Players.bs.mjs";
import * as GridItem from "./GridItem.bs.mjs";
import * as ReactHookForm from "react-hook-form";
import * as JsxRuntime from "react/jsx-runtime";
import * as NewPlayerFormModuleCss from "./new-player-form.module.css";

let styles = NewPlayerFormModuleCss;

function NewPlayerForm(props) {
  let match = React.useState(() => "Hidden");
  let setFormState = match[1];
  let formState = match[0];
  let match$1 = ReactHookForm.useForm();
  let reset = match$1.reset;
  let addCreeper = async name => {
    setFormState(param => "Loading");
    await Players.addPlayer(name);
    return setFormState(param => "Finished");
  };
  let onSubmit = data => {
    addCreeper(data.name);
  };
  React.useEffect(() => {
    if (formState !== "Finished") {
      return;
    }
    reset(undefined);
    let timeoutId = setTimeout(() => setFormState(param => "Hidden"), 4000);
    return () => {
      clearTimeout(timeoutId);
    };
  }, [formState]);
  let showForm = param => setFormState(param => "Visible");
  let content;
  switch (formState) {
    case "Hidden" :
      content = JsxRuntime.jsx("button", {
        children: "+",
        className: styles.addCreeperButton,
        onClick: showForm
      });
      break;
    case "Visible" :
      let newrecord = {...match$1.register("name", {
        required: true
      })};
      content = JsxRuntime.jsxs("form", {
        children: [
          JsxRuntime.jsx("input", (newrecord.placeholder = "Naam", newrecord.className = styles.input + " text-black rounded", newrecord)),
          JsxRuntime.jsx(Button.make, {
            className: styles.submit,
            variant: "Grey",
            children: "Kruiper toevoegen",
            type_: "submit"
          })
        ],
        className: styles.form,
        onSubmit: match$1.handleSubmit(onSubmit)
      });
      break;
    case "Loading" :
      content = JsxRuntime.jsx("div", {
        children: "...",
        className: styles.status
      });
      break;
    case "Finished" :
      content = JsxRuntime.jsx("div", {
        children: "✔︎",
        className: styles.status,
        onClick: showForm
      });
      break;
  }
  return JsxRuntime.jsx(GridItem.make, {
    active: false,
    children: content,
    className: styles.addCreeper
  });
}

let make = NewPlayerForm;

export {
  make,
}
/* styles Not a pure module */
