// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function make(props) {
  let newrecord = {...props};
  return JsxRuntime.jsxs("svg", (newrecord.xmlns = "http://www.w3.org/2000/svg", newrecord.viewBox = "-0.5 -0.5 16 16", newrecord.width = "1em", newrecord.height = "1em", newrecord["aria-hidden"] = true, newrecord.children = [
    JsxRuntime.jsx("path", {
      d: "M.938 2.131h13.124V12.87H.938Z",
      fill: "none",
      stroke: "currentColor",
      strokeMiterlimit: "10"
    }),
    JsxRuntime.jsx("path", {
      d: "M11.675 5.713h2.387v3.58h-2.387ZM.938 5.713h2.387v3.58H.937ZM5.713 7.5a1.787 1.787 0 1 0 3.575 0 1.787 1.787 0 1 0-3.576 0M7.5 2.131v3.582M7.5 9.287v3.582",
      fill: "none",
      stroke: "currentColor",
      strokeMiterlimit: "10"
    })
  ], newrecord));
}

export {
  make,
}
/* react/jsx-runtime Not a pure module */
