// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stats from "../helpers/Stats.bs.mjs";
import * as React from "react";
import * as Button from "./Button.bs.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as DaysWithout from "../helpers/DaysWithout.bs.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as DifferenceInDays from "date-fns/differenceInDays";

function StatsModal(props) {
  var setShow = props.setShow;
  var show = props.show;
  var stats = Stats.useStats();
  var match = DaysWithout.useDaysWithout();
  var daysSince = DifferenceInDays.differenceInDays(new Date(), match[1]);
  var blue = stats.totalBlueWins;
  var red = stats.totalRedWins;
  var bluePercentages = (blue / (blue + red) * 100).toString();
  React.useEffect((function () {
          if (!show) {
            return ;
          }
          var handleKeyDown = function ($$event) {
            var key = Core__Option.getOr(Caml_option.nullable_to_opt($$event.key), "");
            if (key === "Escape") {
              return setShow(function (param) {
                          return false;
                        });
            }
            
          };
          document.addEventListener("keydown", handleKeyDown);
          return (function () {
                    document.removeEventListener("keydown", handleKeyDown);
                  });
        }), [show]);
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                show ? JsxRuntime.jsx("div", {
                        className: "fixed inset-0 z-[199] bg-black/20",
                        onClick: (function (param) {
                            setShow(function (param) {
                                  return false;
                                });
                          })
                      }) : null,
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("header", {
                              children: JsxRuntime.jsx(Button.make, {
                                    variant: "Blue",
                                    onClick: (function (param) {
                                        setShow(function (s) {
                                              return !s;
                                            });
                                      }),
                                    children: "Terug"
                                  })
                            }),
                        JsxRuntime.jsx("h2", {
                              children: "Foosball",
                              className: "pt-5 mb-4 block text-2xl"
                            }),
                        JsxRuntime.jsxs("ul", {
                              children: [
                                JsxRuntime.jsxs("li", {
                                      children: [
                                        JsxRuntime.jsx("strong", {
                                              children: "Total games: "
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: stats.totalGames
                                            })
                                      ],
                                      className: "p-2 rounded border-white/20 border bg-white/5 flex justify-between"
                                    }),
                                JsxRuntime.jsxs("li", {
                                      children: [
                                        JsxRuntime.jsx("strong", {
                                              children: "Blue wins: "
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: stats.totalBlueWins
                                            })
                                      ],
                                      className: "p-2 rounded border-white/20 border bg-white/5 flex justify-between"
                                    }),
                                JsxRuntime.jsxs("li", {
                                      children: [
                                        JsxRuntime.jsx("strong", {
                                              children: "Red wins: "
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: stats.totalRedWins
                                            })
                                      ],
                                      className: "p-2 rounded border-white/20 border bg-white/5 flex justify-between"
                                    }),
                                JsxRuntime.jsxs("li", {
                                      children: [
                                        JsxRuntime.jsx("strong", {
                                              children: "7-0's: "
                                            }),
                                        JsxRuntime.jsx("span", {
                                              children: stats.totalAbsoluteWins
                                            })
                                      ],
                                      className: "p-2 rounded border-white/20 border bg-white/5 flex justify-between"
                                    })
                              ],
                              className: "grid grid-cols-2 gap-2"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("div", {
                                    className: "rounded-full aspect-square w-[300px] my-4 mx-auto shadow-inner shadow-orange-50",
                                    style: {
                                      background: "conic-gradient(#86b7ff, #1c77ff " + bluePercentages + "%, #ff3e6e " + bluePercentages + "%, #ff0055)"
                                    }
                                  })
                            }),
                        JsxRuntime.jsx("hr", {}),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: "Darts",
                                      className: "pt-5 mb-4 block text-2xl"
                                    }),
                                JsxRuntime.jsx("ul", {
                                      children: JsxRuntime.jsxs("li", {
                                            children: [
                                              JsxRuntime.jsx("strong", {
                                                    children: "Total games: "
                                                  }),
                                              JsxRuntime.jsx("span", {
                                                    children: stats.totalDartsGames
                                                  })
                                            ],
                                            className: "p-2 rounded border-white/20 border bg-white/5 flex justify-between"
                                          }),
                                      className: "grid grid-cols-2 gap-2"
                                    }),
                                JsxRuntime.jsx("br", {})
                              ]
                            }),
                        JsxRuntime.jsx("hr", {}),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("h2", {
                                      children: match[0],
                                      className: "pt-5 text-3xl text-center"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: daysSince.toString(),
                                      className: "text-[160px] font-handwritten"
                                    }),
                                JsxRuntime.jsx(Button.make, {
                                      variant: "Blue",
                                      onClick: (function (param) {
                                          DaysWithout.reset();
                                        }),
                                      children: "Reset"
                                    })
                              ],
                              className: "flex justify-center items-center flex-col gap-2"
                            }),
                        JsxRuntime.jsx("div", {
                              className: "flex-1"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("a", {
                                    children: "Contribute on GitHub",
                                    href: "https://github.com/cornedor/creeplogger"
                                  })
                            })
                      ],
                      className: "modal flex flex-col",
                      style: {
                        transform: show ? "translateX(0)" : "translateX(-100%)"
                      },
                      onMouseDown: (function ($$event) {
                          $$event.stopPropagation();
                        })
                    })
              ]
            });
}

var make = StatsModal;

export {
  make ,
}
/* Stats Not a pure module */
