// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "./Button.bs.mjs";
import * as Players from "../helpers/Players.bs.mjs";
import * as GameTypes from "../helpers/GameTypes.bs.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function StatsModal(props) {
  var setShow = props.setShow;
  var gameTypes = GameTypes.useGameTypes();
  var players = Players.useAllPlayers(undefined, undefined);
  var gameTypeHead = gameTypes.map(function (gameType) {
        return JsxRuntime.jsx("th", {
                    children: JsxRuntime.jsx("span", {
                          children: gameType.name,
                          className: "vertical-lr"
                        }),
                    className: "text-center py-2 even:bg-slate-50/10 "
                  }, gameType.name);
      });
  var playerRows = players.map(function (player) {
        var gamesPlayed = gameTypes.map(function (gameType) {
              var hasPlayed = player.gameTypes.includes(gameType.name);
              if (hasPlayed) {
                return JsxRuntime.jsx("td", {
                            children: "✅",
                            className: "text-center even:bg-slate-50/10"
                          }, gameType.name);
              } else {
                return JsxRuntime.jsx("td", {
                            children: "❌",
                            className: "text-center even:bg-slate-50/10"
                          }, gameType.name);
              }
            });
        return JsxRuntime.jsxs("tr", {
                    children: [
                      JsxRuntime.jsx("th", {
                            children: player.name,
                            className: "p-2 text-left "
                          }),
                      gamesPlayed
                    ],
                    className: "odd:bg-slate-50/15"
                  }, player.key);
      });
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsx(Button.make, {
                            variant: "Blue",
                            onClick: (function (param) {
                                setShow(function (s) {
                                      return !s;
                                    });
                              }),
                            children: "Terug"
                          })
                    }),
                JsxRuntime.jsxs("table", {
                      children: [
                        JsxRuntime.jsx("thead", {
                              children: JsxRuntime.jsxs("tr", {
                                    children: [
                                      JsxRuntime.jsx("th", {
                                            children: "",
                                            className: "vertical-lr"
                                          }),
                                      gameTypeHead
                                    ]
                                  })
                            }),
                        JsxRuntime.jsx("tbody", {
                              children: playerRows
                            })
                      ],
                      className: "table-auto"
                    }),
                JsxRuntime.jsx("div", {
                      className: "flex-1"
                    })
              ],
              className: "modal flex flex-col",
              style: {
                transform: props.show ? "translateX(0)" : "translateX(-100%)"
              }
            });
}

var make = StatsModal;

export {
  make ,
}
/* Button Not a pure module */
