// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cn from "rescript-classnames/src/Cn.bs.mjs";
import * as React from "react";
import * as Button from "./Button.bs.mjs";
import * as Header from "./Header.bs.mjs";
import * as GridItem from "./GridItem.bs.mjs";
import * as LoggerStep from "../helpers/LoggerStep.bs.mjs";
import * as NewPlayerForm from "./NewPlayerForm.bs.mjs";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as HeaderModuleCss from "./header.module.css";

let headerStyles = HeaderModuleCss;

function UserGrid(props) {
  let gameMode = props.gameMode;
  let players = props.players;
  let setStep = props.setStep;
  let setSelectedUsers = props.setSelectedUsers;
  let selectedUsers = props.selectedUsers;
  let match = React.useState(() => false);
  let showQueueButtons = match[0];
  let match$1 = React.useState(() => "");
  let searchQuery = match$1[0];
  let match$2 = React.useState(() => {});
  let setBanner = match$2[1];
  let banner = match$2[0];
  let sorted;
  sorted = gameMode === "Foosball" ? players.toSorted((a, b) => b.games - a.games | 0) : players.toSorted((a, b) => b.dartsGames - a.dartsGames | 0);
  let sorted$1 = sorted.filter(item => item.name.toLowerCase().includes(searchQuery.toLowerCase()));
  let players$1 = sorted$1.map(item => {
    let tmp;
    tmp = showQueueButtons ? JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "15m",
            className: "bg-gray-400 border-none cursor-pointer text-3xl text-black rounded-bl ring-inset ring-white hover:ring",
            onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Blue"))
          }),
          JsxRuntime.jsx("button", {
            children: "30m",
            className: "bg-gray-500 border-none cursor-pointer text-3xl text-black ring-inset ring-white hover:ring",
            onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Blue"))
          }),
          JsxRuntime.jsx("button", {
            children: "1h",
            className: "bg-gray-600 border-none cursor-pointer text-3xl text-white ring-inset ring-white hover:ring",
            onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Blue"))
          }),
          JsxRuntime.jsx("button", {
            children: "2h",
            className: "bg-gray-700 border-none cursor-pointer text-3xl text-white rounded-br ring-inset ring-white hover:ring",
            onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Blue"))
          })
        ],
        className: "grid grid-cols-4"
      }) : (
        gameMode === "Foosball" ? JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("button", {
                children: "Blauw",
                className: "bg-[#86b7ff] border-none cursor-pointer text-xl lg:text-3xl rounded-bl text-black plausible-event-name=SelectBlue",
                onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Blue"))
              }),
              JsxRuntime.jsx("button", {
                children: "Rood",
                className: "bg-[#ff8686] border-none cursor-pointer text-xl lg:text-3xl rounded-br text-black plausible-event-name=SelectRed",
                onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Red"))
              })
            ],
            className: "grid grid-cols-2"
          }) : JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("button", {
                children: "Winner",
                className: "bg-green-400 border-none cursor-pointer text-3xl rounded-bl text-black plausible-event-name=SelectWinner",
                onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Blue"))
              }),
              JsxRuntime.jsx("button", {
                children: "Loser",
                className: "bg-[#ff8686] border-none cursor-pointer text-3xl rounded-br text-black plausible-event-name=SelectLoser",
                onClick: param => setSelectedUsers(s => Belt_MapString.set(s, item.key, "Red"))
              })
            ],
            className: "grid grid-cols-2"
          })
      );
    let match = Belt_MapString.get(selectedUsers, item.key);
    let tmp$1;
    tmp$1 = match !== undefined ? (
        match === "Blue" ? (
            gameMode === "Foosball" ? "ring-6 ring-blue" : "ring-6 ring-green-500"
          ) : "ring-6 ring-red"
      ) : "ring-0";
    return JsxRuntime.jsxs(GridItem.make, {
      active: Belt_MapString.has(selectedUsers, item.key),
      children: [
        JsxRuntime.jsx("button", {
          children: JsxRuntime.jsx("b", {
            children: item.name,
            className: "text-ellipsis max-w-full overflow-hidden inline-block p-2 lg:p-3"
          }),
          className: "text-white text-2xl lg:text-3xl min-w-0 max-w-full plausible-event-name=ResetUser",
          onClick: param => setSelectedUsers(s => Belt_MapString.remove(s, item.key))
        }),
        tmp
      ],
      className: Cn.make([
        "rounded-2xl bg-white/10 border border-white/10 backdrop-blur-md shadow-lg hover:shadow-2xl hover:-translate-y-1 transform grid grid-rows-user auto-rows-[1fr] h-[160px] lg:h-[220px] transition-all duration-200 ease-out relative overflow-hidden",
        tmp$1
      ])
    }, item.key);
  });
  let tmp;
  if (banner !== undefined) {
    let pctBlue = Math.round(banner[2] * 100.0);
    let pctRed = Math.round(100.0 - pctBlue);
    tmp = JsxRuntime.jsx("div", {
      children: JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            className: headerStyles.backdrop
          }),
          JsxRuntime.jsx("div", {
            className: headerStyles.backdropEdge
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("strong", {
                children: "Match found",
                className: "text-xl"
              }),
              JsxRuntime.jsx("div", {
                children: "Blue " + (pctBlue | 0).toString() + "% · Red " + (pctRed | 0).toString() + "%",
                className: "text-white/80 text-base md:text-lg"
              })
            ],
            className: "relative z-10 text-white"
          }),
          JsxRuntime.jsx(Button.make, {
            className: "relative z-10",
            variant: "Blue",
            onClick: param => setBanner(param => {}),
            children: "OK"
          })
        ],
        className: headerStyles.glassHeader + " relative px-4 py-4 rounded shadow-[inset_0_1px_0_rgba(255,255,255,0.1)] flex items-center justify-between"
      }),
      className: "fixed left-2 right-2 z-50 bottom-16 md:bottom-4"
    });
  } else {
    tmp = null;
  }
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
    children: [
      JsxRuntime.jsx(Header.make, {
        step: "UserSelection",
        onNextStep: () => setStep(LoggerStep.getNextStep),
        onReset: props.reset,
        disabled: Belt_MapString.size(selectedUsers) <= 1,
        setShowQueueButtons: match[1],
        gameMode: gameMode,
        setGameMode: props.setGameMode,
        searchQuery: searchQuery,
        setSearchQuery: match$1[1],
        setSelectedUsers: setSelectedUsers,
        onMatchFound: (blueTeam, redTeam, pBlue) => setBanner(param => [
          blueTeam,
          redTeam,
          pBlue
        ])
      }),
      JsxRuntime.jsxs("div", {
        children: [
          players$1,
          JsxRuntime.jsx(GridItem.make, {
            active: false,
            children: JsxRuntime.jsx(NewPlayerForm.make, {})
          })
        ],
        className: "grid 2xl:grid-cols-5 xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-3 grid-cols-2 gap-4 lg:gap-10 mt-4 lg:mt-8 px-4 lg:content-padding pb-20 md:pb-4"
      }),
      tmp
    ]
  });
}

let make = UserGrid;

export {
  make,
}
/* headerStyles Not a pure module */
