// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function QueuePage(props) {
  return JsxRuntime.jsx("div", {
              children: "Queue"
            });
}

var make = QueuePage;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
